[gcp_service_account]
type = "service_account"
project_id = "dashboard-analysis-466913"
private_key_id = "945420e3e99487cdb4fe79e4cc59e568974be4eb"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDs3IOLrpHiICc7
qdsA1Ckt3DbSGcpIIfwtFs4kMiv+XjQEMXoZgxR4wL31ohDI3vnhXXJ8RI6/9GYP
A2kpBLJGyGS2mhtDI2wm8iJX/dl8ZXd5LHPQE1X5jSTSYCfpR8yFoOS3Srl+73x4
NdraPW5nawbp5Xyvu5f9dWPaOh0ah2mOm0xa3jSTSROK8cBigrzX72+8kuTGlNYf
q1Zf3fhiEc0FZVfIPXIEU7bTN77dHinz8NYAxUi5rv9C1CuRdqMTdewhFP+8inAt
KXmZshd3ldvOWT4ih8IRqxEDAYvX5NUWGQJBdwnVA3fIy7Vnh+qp+WXpR7RXxu+d
OSb+7rFvAgMBAAECggEABvVF3O4k1WxYE1Iohv6g2r+5+NtOoo39BxnBBSJELh+L
3S2EcuDzg8YjRJf/v3WofnkeIvBpQlwrUOT5reAG+3VVvZxtpOdD81DwaBwY8uAa
qNk76gk2Jan4uMpRHOjzDIdu/2D5qM2Q2jEHINZwOp3Tz7Rr+7xfW5TqAvFNyi7k
yQyMVuY8dZ29mYhXjFZttfCZo+KYdmwZkfWqwrBFzfqARNkVDZPZN5bF12wC6I5d
UIsj33KA3Fj3UdgBadZHurEAitNpAza2JUXCMTsLzyHjv9xY5p+ZIj44beFhACpb
AOzBoioZzxv2WTJ74Gmz8HyAFXESztzt5uDqhVi8oQKBgQD2je31vYAOttx5cDb+
k4mfkNq2b66dLIfsmeeP175HjagTpmlgC7KconsdXvVuhln1ZoxOXAHL36ZK1Iz+
g76bkj6BjJMOijxDNQT11+JQIXHi4NfCkKC/dTYD1izQHmXH31vLxUCB7MICADNS
WRvZvbilPTbv4RZ2Ni3tQthjBQKBgQD174U4srW1KYAZfCykIx2/IEX/2ovRY1rv
wQcwKm+nPi0onxSsLryU73OOR3UGIII1G03uR9FmAr8FjuT/uJ4BEyRUWH4onRZP
iz3pZkkdVbXGiMMhaMIY1AXRlzaA2SrreTc0vySdL3TRcNivGUzCxac/qDA89t4S
2zFVyZCU4wKBgB0lC+MHopKatRc515ZiVFtjYSc9rnNv5yVl0ASl6R1GNn8UJdKv
r05quojvR63n/cxPcfh1UdUKu/qOg5g2dJqpP/BKcLvARX1gUBTLjzoPqgm6sGaU
eBwJu/faInP7k+Z7lbtRtt1k4k4gPfDXDb7AeYo24T6b6e7RWr54L2INAoGAcgIo
QwFthN8JOEc9NpXk204txQ7eFCI37L8SAv0ZJ3GGY7djUPKVj4F1kzaDBGUbl1zi
Ap0ecGjDfuMgO3+tF5h1Ffiz+0XfKt7Ew6ccK9Io4zFRK/KxT+syC1hK9u41nFVk
Bzq40XlHcTQb7wgOcphIERV5zzkt95XPSBKZyLsCgYAODX7bP34/PfJbeTdvd9Wa
BR79Ek+3BgQlwSNvWEE9dxULAKJcMbCUKruwF5OOjZgbKoeo0GwtefQG63Pwlumt
kdOuu503XEXjiYxHXMroO91id/o+7RTyMP1ev/JJ98U8IK8Diuqe1PAQT22At8bG
tJykyxG9/HE3LUyRW2jvdQ==
-----END PRIVATE KEY-----
"""
client_email = "streamlit-app-user@dashboard-analysis-466913.iam.gserviceaccount.com"
client_id = "105641173918209499800"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-app-user%40dashboard-analysis-466913.iam.gserviceaccount.com"

[gcp_config]
BUCKET_NAME = "quality-guidelines-bucket"